### ISSUE TITLE
[Bug]: v1.0.0-beta.5 plugin crashed!

### ISSUE THREAD

**Issue by premadhas** [TiVo/terraform-provider-splunk-itsi#231]
## Description
The terraform code was working and made a few changes and was working but while the time doing other changes and plan Plugin is getting crashed, details attached in the logs section.

## Steps to Reproduce
terraform plan

## Expected Behavior
It suppose to give the plan output and apply the changes

## Current Behavior
Crashing

### ITSI Terraform Provider version

1.0.0-beta.5 and 1.0.0-beta.4

## Environment
Terraform version and OS: Mac - Ventura 13.3.1
ITSI version : 4.16.0
Splunk version: Cloud Version:9.0.2303.201

### Relevant log output

```shell
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-splunk-itsi_v1.0.0-beta.5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x17ffc99]

goroutine 77 [running]:
github.com/tivo/terraform-provider-splunk-itsi/provider.(*dataSourceEntityType).Read(0xc000252150, {0x1b4f100, 0xc0001fb410}, {{{{0x1b53bc8, 0xc0001fbef0}, {0x18fcbe0, 0xc0001fbc50}}, {0x1b54e00, 0xc000330580}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/tivo/terraform-provider-splunk-itsi/provider/datasource_entity_type.go:83 +0x1d9
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc000155600, {0x1b4f100, 0xc0001fb410}, 0xc0001fb500, 0xc000299440)
        github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/fwserver/server_readdatasource.go:79 +0x4ae
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc000155600, {0x1b4f100?, 0xc0001fb2c0?}, 0xc0000b0160)
        github.com/hashicorp/terraform-plugin-framework@v1.3.0/internal/proto6server/server_readdatasource.go:55 +0x42f
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadDataSource({0xc000344a50, 0xc000344ab0, {0xc000360aa0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadDataSource.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc000436000, {0x1b4f100?, 0xc0001fa150?}, 0xc0002d80f0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:656 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x19c7bc0?, 0xc000436000}, {0x1b4f100, 0xc0001fa150}, 0xc000252000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:455 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ca1e0, {0x1b53eb8, 0xc00039d860}, 0xc0001f0120, 0xc00042b350, 0x20aee90, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001ca1e0, {0x1b53eb8, 0xc00039d860}, 0xc0001f0120, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

Error: The terraform-provider-splunk-itsi_v1.0.0-beta.5 plugin crashed!
```

**Comment by dmitrykruglov** [comment]
Hi @premadhas,
thanks for the bug report!
There was a missing check for the case when an entity type is not found, which is most likely what had happened in your case and caused this crash. I have just fixed it in #232, and released [v1.0.0-beta.6](https://github.com/TiVo/terraform-provider-splunk-itsi/releases/tag/v1.0.0-beta.6) with the fix.
